stages:
  - linting

jsonlint:
  stage: linting
  image: pipelinecomponents/jsonlint:0.19.4
  script:
    - |
      find . -not -path './.git/*' -name '*.json' -type f -print0 |
      parallel --will-cite -k -0 -n1 jsonlint -q
